// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
)

const createNewUser = `-- name: CreateNewUser :one
INSERT INTO users(username, email, created_at, updated_at) VALUES (
    ?,
    ?,
    DATETIME('now'),
    DATETIME('now')
)
RETURNING id, username, email, created_at, updated_at
`

type CreateNewUserParams struct {
	Username string
	Email    string
}

func (q *Queries) CreateNewUser(ctx context.Context, arg CreateNewUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createNewUser, arg.Username, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
